name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: multiple command
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.TESTSITEHOST_HOST }}
          username: ${{ secrets.TESTSITEHOST_USERNAME }}
          key: ${{ secrets.TESTSITEHOST_PRIVATE_KEY }}
          port: ${{ secrets.TESTSITEHOST_PORT }}
          script: "
            ls -al &&
            cd /container/application/gitdirectory
            "
